# Generated by Django 5.1.3 on 2024-12-02 19:18

import currencies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_rate_date_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[currencies.models.len_equal_3]),
        ),
    ]
